```{r}
#lade csv file als data.frame rawData
rawData = read.csv("/Users/Selina/Documents/Uni/BA/Plastik/Testung/Für R/Kosten im Vergleich/Datentabelle_R_Kosten.csv", header = TRUE, stringsAsFactors = FALSE)

#erstelle neue Spalte mit Produkttyp ("Plastik" vs "Alternativ")
rawData$Typ = "Plastik"
rawData[startsWith(rawData$Produkt, "A"), "Typ"] = "Alternativ"

#erstelle neue Spalte mit Produktkategorie
rawData$Kategorie = substr(rawData$Produkt, 2, 2)
rawData$Kategorie = as.integer(rawData$Kategorie)

print(rawData)
```
```{r}
#Datenformat normieren
data = melt(rawData, id.var = c("VP", "Produkt", "Art", "Typ", "Kategorie"), variable.name = "Frage", value.name = "Wert")
data$Frage = as.character(data$Frage)

#Daten anzeigen
head(data)

#usammenfassung anzeigen
summary(data)
```


```{r}
#Funktion für line chart für ein feature
drawAvgDataFeatureByProductLineChart = function(feature, typ){
  # Datenset selektieren
  dataFeature = data[data$Frage == feature & data$Typ == typ,]
  # Durchschnitt pro Frage berechnen
  avgDataFeatureByProduct = with(dataFeature, aggregate(Wert ~ Produkt + Art + Typ + Frage, FUN = mean))
  # Line Charts für avgDataFeatureByProduct erstellen
  avgDataFeatureByProductLineChart = ggplot(avgDataFeatureByProduct, aes(x = Art, y = Wert, label = Produkt, group = Produkt)) + 
    geom_line() +
    geom_point() +
    geom_label_repel()
  
  print(avgDataFeatureByProduct)
  print(avgDataFeatureByProductLineChart)
}
```

```{r}
#erstelle line chart für B2_Kosten
drawAvgDataFeatureByProductLineChart("Kosten", "Plastik")

ggsave("B2_Kosten_Plastik.png")

```

```{r}
#erstelle line chart für B2_Kosten
drawAvgDataFeatureByProductLineChart("Kosten", "Alternativ")

ggsave("B2_Kosten_Alternativ.png")

```

```{r}
#Vergleichstabelle für B2_Kosten_Klingen
with(data[data$Frage == "Klingen" & data$Kategorie == 4,], aggregate(Wert ~ Typ + Art, FUN = mean))
```